# Copyright 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Lorenzo Leone <lleone@iis.ee.ethz.ch>
# Sergio Mazzola <smazzola@iis.ee.ethz.ch>


variables:
  # Enable colors in CI terminal
  TERM: ansi
  FORCE_COLOR: 1
  BINARY_DIR: ./sw/tests

default:
  before_script:
      # Install python virtual environment
    - source iis-env.sh
    - env

stages:
  - init
  - build
  - test

.base:
  artifacts:
    when: always
    expire_in: 1 week

# Pull the cached bender checkout
.cache-deps:
  cache: &global_cache
    key:
      files:
        - Bender.lock
    paths:
      - .bender
    policy: pull

init-deps:
  extends: .base
  stage: init
  script:
    # Check out the biggest bender dependencies serially
    # to avoid rate limiting issues
    - bender path cheshire
    - bender path cva6
    - bender path axi
    - bender path idma
    - bender path snitch_cluster
    - bender path memory_island
    # Pre-init cheshire's large submodules serially to avoid rate limiting
    - git -C "$(bender path cheshire)" submodule update --init sw/deps/cva6-sdk
    - git -C "$(bender path cheshire)" submodule update --init sw/deps/printf
    # Collect bender sourcess
    - bender checkout
    # bender checkout sometimes fails,
  cache:
    <<: *global_cache
    policy: pull-push
    # due to rate limiting of github
  retry: 1


vsim-build:
  extends:
    - .base
    - .cache-deps
  stage: build
  needs:
    - init-deps
  script:
    # Build hardware
    - make chs-hw-init
    - make sn-hw-all
    # Build Chimera SW
    - make chim-sw
    # Build Chimera Bootrom
    - make chim-bootrom-init
    # Compile SoC in vsim
    - make chim-sim
  artifacts:
    paths: [ "hw", "sw", "target/sim" ]
    expire_in: 3 days

vsim-test:
  extends:
    - .base
    - .cache-deps
  stage: test
  needs: [ vsim-build ]
  parallel:
    matrix:
      - TESTNAME:
          - testCluster
          - testClusterOffload
          - testMemBypass
          - testPeripheralsGating
          - testHyperbusAddr
          - testCfgBootAddr
  script:
    - make chim-run-batch BINARY=$BINARY_DIR/$TESTNAME.memisl.elf VSIM_FLAGS="-l $TESTNAME.transcript"
    - ./scripts/vsim_ret_error.sh $TESTNAME.transcript
  dependencies:
    - vsim-build
  artifacts:
    paths: [ "hw", "sw", "target/sim" ]
    exclude: [ "target/sim/vsim/work/**/*", "target/sim/vsim/work" ]
    expire_in: 4 weeks
