# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["setuptools==68.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chimera"
version = "1.0.0"
description = "A Flexible Multi-Accelerator Framework for Heterogeneous SoC Integration"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Lorenzo Leone", email = "lleone@iis.ee.ethz.ch" }]

dependencies = [
  "hjson",
  "tabulate",
  "pyyaml",
  "mako",
  "jsonref",
  "jsonschema",
  "flatdict",
  "json5",
  "peakrdl",
  "peakrdl-rawheader @ git+https://github.com/colluca/PeakRDL-rawheader.git@7b8dbc9ad5854dc1cdaf36d4ea024c29ffb00a4c",
  "peakrdl-markdown",
]

[tool.setuptools]
packages = []
include-package-data = false
