// Copyright 2024 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module chimera_reg_top (
        input wire clk,
        input wire arst_n,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [6:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        output chimera_reg_pkg::chimera_soc_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [6:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[6:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic snitch_boot_addr;
        logic snitch_configurable_boot_addr;
        logic snitch_intr_handler_addr;
        logic snitch_cluster_return[5];
        logic reset_cluster[5];
        logic cluster_clk_gate_en[5];
        logic wide_mem_cluster_bypass[5];
        logic cluster_busy[5];
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [6:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.snitch_boot_addr = cpuif_req_masked & (cpuif_addr == 7'h0);
        decoded_reg_strb.snitch_configurable_boot_addr = cpuif_req_masked & (cpuif_addr == 7'h4);
        decoded_reg_strb.snitch_intr_handler_addr = cpuif_req_masked & (cpuif_addr == 7'h8);
        for(int i0=0; i0<5; i0++) begin
            decoded_reg_strb.snitch_cluster_return[i0] = cpuif_req_masked & (cpuif_addr == 7'hc + (7)'(i0) * 7'h4);
        end
        for(int i0=0; i0<5; i0++) begin
            decoded_reg_strb.reset_cluster[i0] = cpuif_req_masked & (cpuif_addr == 7'h20 + (7)'(i0) * 7'h4);
        end
        for(int i0=0; i0<5; i0++) begin
            decoded_reg_strb.cluster_clk_gate_en[i0] = cpuif_req_masked & (cpuif_addr == 7'h34 + (7)'(i0) * 7'h4);
        end
        for(int i0=0; i0<5; i0++) begin
            decoded_reg_strb.wide_mem_cluster_bypass[i0] = cpuif_req_masked & (cpuif_addr == 7'h48 + (7)'(i0) * 7'h4);
        end
        for(int i0=0; i0<5; i0++) begin
            decoded_reg_strb.cluster_busy[i0] = cpuif_req_masked & (cpuif_addr == 7'h5c + (7)'(i0) * 7'h4);
        end
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } value;
        } snitch_boot_addr;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } value;
        } snitch_configurable_boot_addr;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } value;
        } snitch_intr_handler_addr;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } value;
        } snitch_cluster_return[5];
        struct {
            struct {
                logic next;
                logic load_next;
            } value;
        } reset_cluster[5];
        struct {
            struct {
                logic next;
                logic load_next;
            } value;
        } cluster_clk_gate_en[5];
        struct {
            struct {
                logic next;
                logic load_next;
            } value;
        } wide_mem_cluster_bypass[5];
        struct {
            struct {
                logic next;
                logic load_next;
            } value;
        } cluster_busy[5];
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [31:0] value;
            } value;
        } snitch_boot_addr;
        struct {
            struct {
                logic [31:0] value;
            } value;
        } snitch_configurable_boot_addr;
        struct {
            struct {
                logic [31:0] value;
            } value;
        } snitch_intr_handler_addr;
        struct {
            struct {
                logic [31:0] value;
            } value;
        } snitch_cluster_return[5];
        struct {
            struct {
                logic value;
            } value;
        } reset_cluster[5];
        struct {
            struct {
                logic value;
            } value;
        } cluster_clk_gate_en[5];
        struct {
            struct {
                logic value;
            } value;
        } wide_mem_cluster_bypass[5];
        struct {
            struct {
                logic value;
            } value;
        } cluster_busy[5];
    } field_storage_t;
    field_storage_t field_storage;

    // Field: chimera_soc_regs.snitch_boot_addr.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.snitch_boot_addr.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.snitch_boot_addr && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.snitch_boot_addr.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.snitch_boot_addr.value.next = next_c;
        field_combo.snitch_boot_addr.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.snitch_boot_addr.value.value <= 32'hbadcab1e;
        end else begin
            if(field_combo.snitch_boot_addr.value.load_next) begin
                field_storage.snitch_boot_addr.value.value <= field_combo.snitch_boot_addr.value.next;
            end
        end
    end
    assign hwif_out.snitch_boot_addr.value.value = field_storage.snitch_boot_addr.value.value;
    // Field: chimera_soc_regs.snitch_configurable_boot_addr.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.snitch_configurable_boot_addr.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.snitch_configurable_boot_addr && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.snitch_configurable_boot_addr.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.snitch_configurable_boot_addr.value.next = next_c;
        field_combo.snitch_configurable_boot_addr.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.snitch_configurable_boot_addr.value.value <= 32'h30000000;
        end else begin
            if(field_combo.snitch_configurable_boot_addr.value.load_next) begin
                field_storage.snitch_configurable_boot_addr.value.value <= field_combo.snitch_configurable_boot_addr.value.next;
            end
        end
    end
    assign hwif_out.snitch_configurable_boot_addr.value.value = field_storage.snitch_configurable_boot_addr.value.value;
    // Field: chimera_soc_regs.snitch_intr_handler_addr.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.snitch_intr_handler_addr.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.snitch_intr_handler_addr && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.snitch_intr_handler_addr.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.snitch_intr_handler_addr.value.next = next_c;
        field_combo.snitch_intr_handler_addr.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.snitch_intr_handler_addr.value.value <= 32'hbadcab1e;
        end else begin
            if(field_combo.snitch_intr_handler_addr.value.load_next) begin
                field_storage.snitch_intr_handler_addr.value.value <= field_combo.snitch_intr_handler_addr.value.next;
            end
        end
    end
    assign hwif_out.snitch_intr_handler_addr.value.value = field_storage.snitch_intr_handler_addr.value.value;
    for(genvar i0=0; i0<5; i0++) begin
        // Field: chimera_soc_regs.snitch_cluster_return[].value
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.snitch_cluster_return[i0].value.value;
            load_next_c = '0;
            if(decoded_reg_strb.snitch_cluster_return[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.snitch_cluster_return[i0].value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            field_combo.snitch_cluster_return[i0].value.next = next_c;
            field_combo.snitch_cluster_return[i0].value.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.snitch_cluster_return[i0].value.value <= 32'h0;
            end else begin
                if(field_combo.snitch_cluster_return[i0].value.load_next) begin
                    field_storage.snitch_cluster_return[i0].value.value <= field_combo.snitch_cluster_return[i0].value.next;
                end
            end
        end
        assign hwif_out.snitch_cluster_return[i0].value.value = field_storage.snitch_cluster_return[i0].value.value;
    end
    for(genvar i0=0; i0<5; i0++) begin
        // Field: chimera_soc_regs.reset_cluster[].value
        always_comb begin
            automatic logic [0:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.reset_cluster[i0].value.value;
            load_next_c = '0;
            if(decoded_reg_strb.reset_cluster[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.reset_cluster[i0].value.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
                load_next_c = '1;
            end
            field_combo.reset_cluster[i0].value.next = next_c;
            field_combo.reset_cluster[i0].value.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.reset_cluster[i0].value.value <= 1'h1;
            end else begin
                if(field_combo.reset_cluster[i0].value.load_next) begin
                    field_storage.reset_cluster[i0].value.value <= field_combo.reset_cluster[i0].value.next;
                end
            end
        end
        assign hwif_out.reset_cluster[i0].value.value = field_storage.reset_cluster[i0].value.value;
    end
    for(genvar i0=0; i0<5; i0++) begin
        // Field: chimera_soc_regs.cluster_clk_gate_en[].value
        always_comb begin
            automatic logic [0:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.cluster_clk_gate_en[i0].value.value;
            load_next_c = '0;
            if(decoded_reg_strb.cluster_clk_gate_en[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.cluster_clk_gate_en[i0].value.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
                load_next_c = '1;
            end
            field_combo.cluster_clk_gate_en[i0].value.next = next_c;
            field_combo.cluster_clk_gate_en[i0].value.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.cluster_clk_gate_en[i0].value.value <= 1'h1;
            end else begin
                if(field_combo.cluster_clk_gate_en[i0].value.load_next) begin
                    field_storage.cluster_clk_gate_en[i0].value.value <= field_combo.cluster_clk_gate_en[i0].value.next;
                end
            end
        end
        assign hwif_out.cluster_clk_gate_en[i0].value.value = field_storage.cluster_clk_gate_en[i0].value.value;
    end
    for(genvar i0=0; i0<5; i0++) begin
        // Field: chimera_soc_regs.wide_mem_cluster_bypass[].value
        always_comb begin
            automatic logic [0:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.wide_mem_cluster_bypass[i0].value.value;
            load_next_c = '0;
            if(decoded_reg_strb.wide_mem_cluster_bypass[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.wide_mem_cluster_bypass[i0].value.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
                load_next_c = '1;
            end
            field_combo.wide_mem_cluster_bypass[i0].value.next = next_c;
            field_combo.wide_mem_cluster_bypass[i0].value.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.wide_mem_cluster_bypass[i0].value.value <= 1'h0;
            end else begin
                if(field_combo.wide_mem_cluster_bypass[i0].value.load_next) begin
                    field_storage.wide_mem_cluster_bypass[i0].value.value <= field_combo.wide_mem_cluster_bypass[i0].value.next;
                end
            end
        end
        assign hwif_out.wide_mem_cluster_bypass[i0].value.value = field_storage.wide_mem_cluster_bypass[i0].value.value;
    end
    for(genvar i0=0; i0<5; i0++) begin
        // Field: chimera_soc_regs.cluster_busy[].value
        always_comb begin
            automatic logic [0:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.cluster_busy[i0].value.value;
            load_next_c = '0;
            if(decoded_reg_strb.cluster_busy[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.cluster_busy[i0].value.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
                load_next_c = '1;
            end
            field_combo.cluster_busy[i0].value.next = next_c;
            field_combo.cluster_busy[i0].value.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.cluster_busy[i0].value.value <= 1'h1;
            end else begin
                if(field_combo.cluster_busy[i0].value.load_next) begin
                    field_storage.cluster_busy[i0].value.value <= field_combo.cluster_busy[i0].value.next;
                end
            end
        end
        assign hwif_out.cluster_busy[i0].value.value = field_storage.cluster_busy[i0].value.value;
    end

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [6:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 7'h0) begin
            readback_data_var[31:0] = field_storage.snitch_boot_addr.value.value;
        end
        if(rd_mux_addr == 7'h4) begin
            readback_data_var[31:0] = field_storage.snitch_configurable_boot_addr.value.value;
        end
        if(rd_mux_addr == 7'h8) begin
            readback_data_var[31:0] = field_storage.snitch_intr_handler_addr.value.value;
        end
        for(int i0=0; i0<5; i0++) begin
            if(rd_mux_addr == 7'hc + (7)'(i0) * 7'h4) begin
                readback_data_var[31:0] = field_storage.snitch_cluster_return[i0].value.value;
            end
        end
        for(int i0=0; i0<5; i0++) begin
            if(rd_mux_addr == 7'h20 + (7)'(i0) * 7'h4) begin
                readback_data_var[0] = field_storage.reset_cluster[i0].value.value;
            end
        end
        for(int i0=0; i0<5; i0++) begin
            if(rd_mux_addr == 7'h34 + (7)'(i0) * 7'h4) begin
                readback_data_var[0] = field_storage.cluster_clk_gate_en[i0].value.value;
            end
        end
        for(int i0=0; i0<5; i0++) begin
            if(rd_mux_addr == 7'h48 + (7)'(i0) * 7'h4) begin
                readback_data_var[0] = field_storage.wide_mem_cluster_bypass[i0].value.value;
            end
        end
        for(int i0=0; i0<5; i0++) begin
            if(rd_mux_addr == 7'h5c + (7)'(i0) * 7'h4) begin
                readback_data_var[0] = field_storage.cluster_busy[i0].value.value;
            end
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
