// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module chimera_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 6
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output chimera_reg_pkg::chimera_reg2hw_t reg2hw, // Write
  input  chimera_reg_pkg::chimera_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import chimera_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [31:0] snitch_boot_addr_qs;
  logic [31:0] snitch_boot_addr_wd;
  logic snitch_boot_addr_we;
  logic [31:0] snitch_intr_handler_addr_qs;
  logic [31:0] snitch_intr_handler_addr_wd;
  logic snitch_intr_handler_addr_we;
  logic [31:0] snitch_cluster_1_return_qs;
  logic [31:0] snitch_cluster_2_return_qs;
  logic [31:0] snitch_cluster_3_return_qs;
  logic [31:0] snitch_cluster_4_return_qs;
  logic [31:0] snitch_cluster_5_return_qs;
  logic cluster_1_clk_gate_en_qs;
  logic cluster_1_clk_gate_en_wd;
  logic cluster_1_clk_gate_en_we;
  logic cluster_2_clk_gate_en_qs;
  logic cluster_2_clk_gate_en_wd;
  logic cluster_2_clk_gate_en_we;
  logic cluster_3_clk_gate_en_qs;
  logic cluster_3_clk_gate_en_wd;
  logic cluster_3_clk_gate_en_we;
  logic cluster_4_clk_gate_en_qs;
  logic cluster_4_clk_gate_en_wd;
  logic cluster_4_clk_gate_en_we;
  logic cluster_5_clk_gate_en_qs;
  logic cluster_5_clk_gate_en_wd;
  logic cluster_5_clk_gate_en_we;

  // Register instances
  // R[snitch_boot_addr]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'hbadcab1e)
  ) u_snitch_boot_addr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (snitch_boot_addr_we),
    .wd     (snitch_boot_addr_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.snitch_boot_addr.q ),

    // to register interface (read)
    .qs     (snitch_boot_addr_qs)
  );


  // R[snitch_intr_handler_addr]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'hbadcab1e)
  ) u_snitch_intr_handler_addr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (snitch_intr_handler_addr_we),
    .wd     (snitch_intr_handler_addr_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.snitch_intr_handler_addr.q ),

    // to register interface (read)
    .qs     (snitch_intr_handler_addr_qs)
  );


  // R[snitch_cluster_1_return]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_snitch_cluster_1_return (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.snitch_cluster_1_return.de),
    .d      (hw2reg.snitch_cluster_1_return.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.snitch_cluster_1_return.q ),

    // to register interface (read)
    .qs     (snitch_cluster_1_return_qs)
  );


  // R[snitch_cluster_2_return]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_snitch_cluster_2_return (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.snitch_cluster_2_return.de),
    .d      (hw2reg.snitch_cluster_2_return.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.snitch_cluster_2_return.q ),

    // to register interface (read)
    .qs     (snitch_cluster_2_return_qs)
  );


  // R[snitch_cluster_3_return]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_snitch_cluster_3_return (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.snitch_cluster_3_return.de),
    .d      (hw2reg.snitch_cluster_3_return.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.snitch_cluster_3_return.q ),

    // to register interface (read)
    .qs     (snitch_cluster_3_return_qs)
  );


  // R[snitch_cluster_4_return]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_snitch_cluster_4_return (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.snitch_cluster_4_return.de),
    .d      (hw2reg.snitch_cluster_4_return.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.snitch_cluster_4_return.q ),

    // to register interface (read)
    .qs     (snitch_cluster_4_return_qs)
  );


  // R[snitch_cluster_5_return]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_snitch_cluster_5_return (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.snitch_cluster_5_return.de),
    .d      (hw2reg.snitch_cluster_5_return.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.snitch_cluster_5_return.q ),

    // to register interface (read)
    .qs     (snitch_cluster_5_return_qs)
  );


  // R[cluster_1_clk_gate_en]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_cluster_1_clk_gate_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cluster_1_clk_gate_en_we),
    .wd     (cluster_1_clk_gate_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cluster_1_clk_gate_en.q ),

    // to register interface (read)
    .qs     (cluster_1_clk_gate_en_qs)
  );


  // R[cluster_2_clk_gate_en]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_cluster_2_clk_gate_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cluster_2_clk_gate_en_we),
    .wd     (cluster_2_clk_gate_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cluster_2_clk_gate_en.q ),

    // to register interface (read)
    .qs     (cluster_2_clk_gate_en_qs)
  );


  // R[cluster_3_clk_gate_en]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_cluster_3_clk_gate_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cluster_3_clk_gate_en_we),
    .wd     (cluster_3_clk_gate_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cluster_3_clk_gate_en.q ),

    // to register interface (read)
    .qs     (cluster_3_clk_gate_en_qs)
  );


  // R[cluster_4_clk_gate_en]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_cluster_4_clk_gate_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cluster_4_clk_gate_en_we),
    .wd     (cluster_4_clk_gate_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cluster_4_clk_gate_en.q ),

    // to register interface (read)
    .qs     (cluster_4_clk_gate_en_qs)
  );


  // R[cluster_5_clk_gate_en]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_cluster_5_clk_gate_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cluster_5_clk_gate_en_we),
    .wd     (cluster_5_clk_gate_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cluster_5_clk_gate_en.q ),

    // to register interface (read)
    .qs     (cluster_5_clk_gate_en_qs)
  );




  logic [11:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[ 0] = (reg_addr == CHIMERA_SNITCH_BOOT_ADDR_OFFSET);
    addr_hit[ 1] = (reg_addr == CHIMERA_SNITCH_INTR_HANDLER_ADDR_OFFSET);
    addr_hit[ 2] = (reg_addr == CHIMERA_SNITCH_CLUSTER_1_RETURN_OFFSET);
    addr_hit[ 3] = (reg_addr == CHIMERA_SNITCH_CLUSTER_2_RETURN_OFFSET);
    addr_hit[ 4] = (reg_addr == CHIMERA_SNITCH_CLUSTER_3_RETURN_OFFSET);
    addr_hit[ 5] = (reg_addr == CHIMERA_SNITCH_CLUSTER_4_RETURN_OFFSET);
    addr_hit[ 6] = (reg_addr == CHIMERA_SNITCH_CLUSTER_5_RETURN_OFFSET);
    addr_hit[ 7] = (reg_addr == CHIMERA_CLUSTER_1_CLK_GATE_EN_OFFSET);
    addr_hit[ 8] = (reg_addr == CHIMERA_CLUSTER_2_CLK_GATE_EN_OFFSET);
    addr_hit[ 9] = (reg_addr == CHIMERA_CLUSTER_3_CLK_GATE_EN_OFFSET);
    addr_hit[10] = (reg_addr == CHIMERA_CLUSTER_4_CLK_GATE_EN_OFFSET);
    addr_hit[11] = (reg_addr == CHIMERA_CLUSTER_5_CLK_GATE_EN_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(CHIMERA_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(CHIMERA_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(CHIMERA_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(CHIMERA_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(CHIMERA_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(CHIMERA_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(CHIMERA_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(CHIMERA_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(CHIMERA_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(CHIMERA_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(CHIMERA_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(CHIMERA_PERMIT[11] & ~reg_be)))));
  end

  assign snitch_boot_addr_we = addr_hit[0] & reg_we & !reg_error;
  assign snitch_boot_addr_wd = reg_wdata[31:0];

  assign snitch_intr_handler_addr_we = addr_hit[1] & reg_we & !reg_error;
  assign snitch_intr_handler_addr_wd = reg_wdata[31:0];

  assign cluster_1_clk_gate_en_we = addr_hit[7] & reg_we & !reg_error;
  assign cluster_1_clk_gate_en_wd = reg_wdata[0];

  assign cluster_2_clk_gate_en_we = addr_hit[8] & reg_we & !reg_error;
  assign cluster_2_clk_gate_en_wd = reg_wdata[0];

  assign cluster_3_clk_gate_en_we = addr_hit[9] & reg_we & !reg_error;
  assign cluster_3_clk_gate_en_wd = reg_wdata[0];

  assign cluster_4_clk_gate_en_we = addr_hit[10] & reg_we & !reg_error;
  assign cluster_4_clk_gate_en_wd = reg_wdata[0];

  assign cluster_5_clk_gate_en_we = addr_hit[11] & reg_we & !reg_error;
  assign cluster_5_clk_gate_en_wd = reg_wdata[0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = snitch_boot_addr_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[31:0] = snitch_intr_handler_addr_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = snitch_cluster_1_return_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = snitch_cluster_2_return_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = snitch_cluster_3_return_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = snitch_cluster_4_return_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = snitch_cluster_5_return_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[0] = cluster_1_clk_gate_en_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[0] = cluster_2_clk_gate_en_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[0] = cluster_3_clk_gate_en_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[0] = cluster_4_clk_gate_en_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[0] = cluster_5_clk_gate_en_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module chimera_reg_top_intf
#(
  parameter int AW = 6,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output chimera_reg_pkg::chimera_reg2hw_t reg2hw, // Write
  input  chimera_reg_pkg::chimera_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  chimera_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


